services:
  agent-zero:
    container_name: agent-zero
    image: frdel/agent-zero-run:testing
    volumes:
      - ./agent-zero:/a0
    ports:
      - "80:80"
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    networks:
      - agent-network
 
  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    volumes:
      - ./ollama-data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - agent-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]  
 
networks:
  agent-network:
    driver: bridge
